service:
  name: appsync-example
  publish: false # disable auto-publishing to the Serverless platform

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello

custom:
  accountId: abc
  appSync:
    # name:  # defaults to api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    # region: # defaults to provider region
    # mappingTemplatesLocation: # defailts to mapping-templates
    mappingTemplates:
      - dataSource: Users
        type: Query
        field: getUserInfo
        request: "getUserInfo-request-mapping-template.txt"
        response: "getUserInfo-response-mapping-template.txt"
      - dataSource: Users
        type: Query
        field: meInfo
        request: "meInfo-request-mapping-template.txt"
        response: "meInfo-response-mapping-template.txt"
      - dataSource: Tweets
        type: User
        field: topTweet
        request: "topTweet-request-mapping-template.txt"
        response: "topTweet-response-mapping-template.txt"
      - dataSource: Tweets
        type: User
        field: tweets
        request: "tweets-request-mapping-template.txt"
        response: "tweets-response-mapping-template.txt"
      - dataSource: Tweets
        type: Mutation
        field: createTweet
        request: "createTweet-request-mapping-template.txt"
        response: "createTweet-response-mapping-template.txt"
      - dataSource: Tweets
        type: Mutation
        field: deleteTweet
        request: "deleteTweet-request-mapping-template.txt"
        response: "deleteTweet-response-mapping-template.txt"
      - dataSource: Tweets
        type: Mutation
        field: reTweet
        request: "reTweet-request-mapping-template.txt"
        response: "reTweet-response-mapping-template.txt"
      - dataSource: Tweets
        type: Mutation
        field: updateTweet
        request: "updateTweet-request-mapping-template.txt"
        response: "updateTweet-response-mapping-template.txt"
      - dataSource: Users
        type: Mutation
        field: updateUserInfo
        request: "updateUserInfo-request-mapping-template.txt"
        response: "updateUserInfo-response-mapping-template.txt"
    # schema: # defaults schema.graphql
    serviceRole: something/something
    dataSources:
      users:
        type: AMAZON_DYNAMODB
        config:
           tableName: 'users'

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          -
            AttributeName: handle
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: handle
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'Users'
    TweetsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          -
            AttributeName: tweet_id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: tweet_id
            AttributeType: S
          -
            AttributeName: handle
            AttributeType: S
          -
            AttributeName: retweet_count
            AttributeType: N
          -
            AttributeName: created_at
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'Tweets'
        GlobalSecondaryIndexes:
          -
            IndexName: top-index
            KeySchema:
              -
                AttributeName: handle
                KeyType: HASH
              -
                AttributeName: retweet_count
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          -
            IndexName: tweet-index
            KeySchema:
              -
                AttributeName: handle
                KeyType: HASH
              -
                AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Dynamo-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Dynamo-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    # TODO replace with { "Ref" : "AWS::AccountNumber" }
                    - "arn:aws:dynamodb:us-east-1:${self:custom.accountId}:table/Users"
                    - "arn:aws:dynamodb:us-east-1:${self:custom.accountId}:table/Users/*"
                    - "arn:aws:dynamodb:us-east-1:${self:custom.accountId}:table/Tweets"
                    - "arn:aws:dynamodb:us-east-1:${self:custom.accountId}:table/Tweets/*"
